### ISSUE TITLE
Remove old tutorial forked repo

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Tutorial#26]
We should remove the old forked repo at https://github.com/KhronosGroup/VulkanTutorial at some point to avoid confusion.

**Comment by allcreatures** [comment]
As it is a fork, we cannot change the visibility. Okay to delete now, or might there be any changes that should be reviewed first?

**Comment by SaschaWillems** [comment]
We'll review this during our next call. Will let you know about the outcome :)

**Comment by allcreatures** [comment]
This repository has now been archived.
