### ISSUE TITLE
Select a replacement for the comments section

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Tutorial#30]
The original tutorial uses disqus to add a comments section to every chapter and refers to that in the introduction. We should define an alternative to that, to which we then link from the tutorial. The alternatives I can think of are the usual community channels:

- Vulkan discord
- Vulkan forums at Khronos.org
- The discussion section of the repo itself

**Comment by charles-lunarg** [comment]
I think linking to both Vulkan discord & khronos forums would make sense. The discord could create a channel *specifically* for tutorial questions as well, to keep it centralized.

**Comment by SaschaWillems** [comment]
The docs site links at some places where people can discuss this. So no action required.
