### ISSUE TITLE
Add a dark theme

### ISSUE THREAD

**Issue by Pacheco95** [KhronosGroup/Vulkan-Tutorial#33]
The tutorial is very extensive and some chapter takes two or three reads to be understood. The light theme makes it very difficult to read, even using the monitor's eye-saving mode.

**Comment by SaschaWillems** [comment]
The tutorial is only a module for the docs site, so requests like these should go to https://github.com/KhronosGroup/Vulkan-Site/issues

**Comment by Pacheco95** [comment]
I just followed this instruction here https://docs.vulkan.org/tutorial/latest/00_Introduction.html#:~:text=If%20you%20have%20any%20type%20of%20feedback%20on%20the%20tutorial%20and%20site%20itself%2C%20then%20please%20don%E2%80%99t%20hesitate%20to%20submit%20an%20issue%20or%20pull%20request%20to%20the%20GitHub%20repository.

But thanks for the tip

**Comment by SaschaWillems** [comment]
See https://github.com/KhronosGroup/Vulkan-Site/issues/70
