### ISSUE TITLE
Sample Model and Texture 404

### ISSUE THREAD

**Issue by lrbender01** [KhronosGroup/Vulkan-Tutorial#35]
I've been working through this new tutorial and just reached ["Loading models"](https://docs.vulkan.org/tutorial/latest/08_Loading_models.html). The linked files [viking_room.obj](https://docs.vulkan.org/resources/viking_room.obj) and [viking_room.png](https://docs.vulkan.org/resources/viking_room.png) both 404 with the provided links.

I've been able to get both files from this repository but it would be nice if the linked files were available for other users. Thanks!

**Comment by allcreatures** [comment]
While waiting for the files to be added, you can, in theory, grab those two files from here:

https://vulkan-tutorial.com/resources/viking_room.obj
https://vulkan-tutorial.com/resources/viking_room.png

No idea of the same, but seems a good bet.

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. I'll check how we can add these to the Antora build for the tutorial.

**Comment by SaschaWillems** [comment]
This is fixed now and will go public with the next deployment. We usually deploy when the Vulkan Spec is updated.

I'll leave this issue open though, as Antora (the framework we use) will not directly download the files but let's the browser decide, so e.g. the .obj may open in your browser preview and you'd need to download it manually then.

We're working on changing the whole setup and deploy process though and may change the way assets are added in a future update.

**Comment by SaschaWillems** [comment]
Both files are now available through the docs site. Depending on your browser, some of the files (esp. the png) may be displayd instead of downloaded directly and you may have to explicitly save to file to disk.
