### ISSUE TITLE
Hyperlink chain is broken

### ISSUE THREAD

**Issue by attilavs2** [KhronosGroup/Vulkan-Tutorial#43]
At the end of setup step 4 for drawing a triangle there is no link to continue, and since there is no index of the tutorial you have to search for the rest.

**Comment by SaschaWillems** [comment]
Can you post a link to the affected page? 

And the tutorial has a left-side navigation for all pages, or is a page missing there?

**Comment by attilavs2** [comment]
Here : https://docs.vulkan.org/tutorial/latest/03_Drawing_a_triangle/00_Setup/04_Logical_device_and_queues.html
The index only seems to be in the pages or just list the tutorial in general as i said

**Comment by SaschaWillems** [comment]
I have added links to the following chapter for pretty much every chapter. A lot of them didn't have any follow-up links. Some only mentioned a next chapter, but without a link.

This should now be consistent between all chapters.

Note that this change will only become visible at docs.vulkan.org after the next spec update.
